"on":
  - push
name: Test
jobs:
  readmeExamples:
    name: "[TEST] README examples"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run build
      - name: README example
        uses: ./
        with:
          text: Hello
